### ISSUE TITLE
Ambiguity in regex

### ISSUE THREAD

**Issue by fracalo** [joshwcomeau/nice-index#6]
Hello,
nice plugin, really enjoying it !

Recently I saw that a file named `indexHandler.js` was being visualized through the name of the directory;
even if this is a edge case, I think it shouldn't turn on `nice-index`...

I currently made some changes in my fork to make the regex a bit stricter.

I'll send you a pull with my modification so you take a look,  
regards

**Comment by joshwcomeau** [comment]
Hi @fracalo! Thanks for sharing the PR.

I'm afraid I don't quite understand the changes. Can you explain what your regex is doing [here](https://github.com/joshwcomeau/nice-index/pull/7/files#diff-dee137e19b9063205373436329eb93a5L46), specifically the `\\..*` at the end?

**Comment by fracalo** [comment]
Hi,
the `\\.` is literally checking for a period 
(if you weren't using the RegExp constructor it would be just `\.`  - using the constructor you need to escape backslashes)
and `.*` checks any other trailing character, 0 or multiple times (this actually could be dropped off)
[regex101](https://regex101.com/r/JtTki6/1)

As you can see if somebody wanted to activate nice-index with other general filenames (for ex: `style.scss`) you'd just have to add the exact name without extension to [`default`](https://github.com/fracalo/nice-index/blob/3aee133d6111a4e37fea75aa7f48524e4ee7a01b/lib/nice-index.coffee#L12). 

In the future you might want to expose that array as a user configurable setting...

**Comment by joshwcomeau** [comment]
Ahh, that makes sense. Yeah the double-escaped backslash was throwing me off. Thanks!

So, the array of filenames is absolutely exposed in the settings :) The PR that added that array (https://github.com/joshwcomeau/nice-index/pull/5) also ensured it was in the plugin config:

<img width="516" alt="screen shot 2016-11-08 at 6 27 50 am" src="https://cloud.githubusercontent.com/assets/6692932/20097484/af9dcfc4-a57c-11e6-9cbe-5f35a803bda7.png">

I think all config should happen within that array, rather than adding a check to the end of the joined list. For example, I may wish to have nice-index target files without extensions, in which case I'd just enter the literal filename.

That said, I think the default is bugged; the intent was to have it match `index.` with any suffix, not `index` with 0 or more of any characters. If you want to update your PR to change the default value to `index\\.`, I'll gladly accept it and publish :)

**Comment by fracalo** [comment]
Now I see the settings  :)

I made the change and looked into the UI,
atom.config seems to be handling also the escaping of user defined input.

Additional Inputs can be set as regex literal without delimiters (that's what I would expect),
and everything seems to really fall into place, cool!

**Comment by joshwcomeau** [comment]
awesome :) glad to hear it!
